'use client';
import { useEffect, useRef, useState } from 'react';
import Script from 'next/script';
import { X, ShieldCheck, ArrowRight, Menu, LockKeyhole } from 'lucide-react';
import { config, externalUrl, type Locale } from '@/lib/config';
import { dictionaries } from '@/lib/dictionaries';
import { content } from '@/lib/content';
import { navigationSections } from '@/lib/lifecycle';
import { consentKey, disableTracking, enableTracking, hasConsent, track } from '@/lib/tracking';
import { trackingConfig } from '@/lib/tracking-config';
import { DemoLink } from './actions';
export function MobileMenu({locale}:{locale:Locale}){const [open,setOpen]=useState(false);const d=dictionaries[locale];return <div className="mobile-menu"><button className="icon-button" aria-label={open?d.close:d.menu} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X size={21}/>:<Menu size={21}/>}</button>{open&&<nav id="mobile-nav" aria-label={d.label}>{d.nav.map((n,i)=><a key={n} href={`#${navigationSections[i]}`} onClick={()=>setOpen(false)}>{n}<ArrowRight size={16}/></a>)}</nav>}</div>}
export function LegalLink({locale,kind}:{locale:Locale;kind:'privacy'|'cookies'|'legal'}){const c=content[locale];const url={privacy:config.privacyUrl,cookies:config.cookieUrl,legal:config.legalUrl}[kind];return url?<a href={url}>{c[kind]}</a>:<button onClick={()=>window.dispatchEvent(new CustomEvent('open-legal',{detail:kind}))}>{c[kind]}</button>}
export function PreferencesButton({locale}:{locale:Locale}){return <button onClick={()=>window.dispatchEvent(new CustomEvent('open-cookies'))}>{content[locale].preferences}</button>}
export function Interactions({locale}:{locale:Locale}) {
 const d=dictionaries[locale],c=content[locale];const dialog=useRef<HTMLDialogElement>(null);const iframe=useRef<HTMLIFrameElement>(null);
 const [modal,setModal]=useState<'consult'|'cookies'|'privacy'|'legal'|'policy'|null>(null);const [banner,setBanner]=useState(false);const [analytics,setAnalytics]=useState(false);const [query,setQuery]=useState('');const [frameReady,setFrameReady]=useState(false);
 useEffect(()=>{setQuery(location.search);try{localStorage.setItem('rooklyn-language',locale);const saved=JSON.parse(localStorage.getItem(consentKey)||'null');setBanner(!saved||Date.now()-saved.timestamp>180*86400000)}catch{setBanner(true)}setAnalytics(hasConsent());enableTracking();track('hvac_sales_page_viewed',locale);
 const consult=()=>{setFrameReady(false);setModal('consult');track('hvac_lead_form_opened',locale)};const cookies=()=>{setAnalytics(hasConsent());setModal('cookies')};const legal=(event:Event)=>{const kind=(event as CustomEvent).detail;setModal(kind==='cookies'?'policy':kind)};
 window.addEventListener('open-consultation',consult);window.addEventListener('open-cookies',cookies);window.addEventListener('open-legal',legal);
 const target=document.getElementById('impact');let viewed=false;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&!viewed){viewed=true;track('hvac_business_case_viewed',locale)}},{threshold:.2});if(target)observer.observe(target);
 const submission=(event:MessageEvent)=>{if(!config.ghlFormEmbedUrl||event.source!==iframe.current?.contentWindow)return;try{if(event.origin===new URL(config.ghlFormEmbedUrl).origin&&trackingConfig.matchSubmission?.(event.data))track('hvac_lead_form_submitted',locale)}catch{}};
 window.addEventListener('message',submission);
 return()=>{window.removeEventListener('open-consultation',consult);window.removeEventListener('open-cookies',cookies);window.removeEventListener('open-legal',legal);window.removeEventListener('message',submission);observer.disconnect()};
 },[locale]);
 useEffect(()=>{document.body.dataset.cookieBanner=String(banner);return()=>{delete document.body.dataset.cookieBanner}},[banner]);
 useEffect(()=>{if(modal){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[modal]);
 function saveConsent(value:boolean){const was=hasConsent();try{localStorage.setItem(consentKey,JSON.stringify({analytics:value,timestamp:Date.now()}))}catch{}setBanner(false);setModal(null);setAnalytics(value);if(value){enableTracking();if(!was)track('hvac_sales_page_viewed',locale)}else{disableTracking();if(was&&trackingConfig.scriptUrl)window.location.reload()}}
 return <>{banner&&<aside className="cookie-banner" aria-label={c.cookieTitle}><div className="cookie-copy"><ShieldCheck size={22}/><div><strong>{c.cookieTitle}</strong><p>{c.cookieText} <LegalLink locale={locale} kind="cookies"/></p></div></div><div className="cookie-actions"><button onClick={()=>saveConsent(false)}>{c.reject}</button><button onClick={()=>saveConsent(true)}>{c.accept}</button><button className="cookie-config" onClick={()=>setModal('cookies')}>{c.customize}</button></div></aside>}
 <div className="mobile-sticky"><DemoLink locale={locale}>{d.demoCta}</DemoLink></div>
 <dialog ref={dialog} className={`modal ${modal==='consult'?'consult-modal':''}`} aria-labelledby="modal-title" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setModal(null)}}}>
 <button className="modal-close icon-button" aria-label={d.close} onClick={()=>setModal(null)}><X size={22}/></button>
 {modal==='consult'?<><span className="modal-symbol"><WorkflowIcon/></span><h2 id="modal-title">{c.formTitle}</h2><p>{c.formLead}</p>{config.ghlFormEmbedUrl?<div className="embed-wrap">{!frameReady&&<p role="status">{c.formLoading}</p>}<iframe ref={iframe} id="rooklyn-assessment-form" title={c.formTitle} src={externalUrl(config.ghlFormEmbedUrl,locale,query)} data-layout={JSON.stringify({id:'INLINE'})} data-form-id={new URL(config.ghlFormEmbedUrl).pathname.split('/').filter(Boolean).at(-1)} data-form-name="Rooklyn | HVAC | Request Assessment" data-layout-iframe-id="rooklyn-assessment-form" data-cookie-consent="true" data-cookie-consent-provider="auto" style={{display:'block',borderRadius:8}} onLoad={()=>setFrameReady(true)} referrerPolicy="strict-origin-when-cross-origin"/><Script id="rooklyn-ghl-form-embed" src="https://link.msgsndr.com/js/form_embed.js" strategy="afterInteractive"/><a href={externalUrl(config.ghlFormEmbedUrl,locale,query)} className="text-link">{c.formFallback}<ArrowRight size={15}/></a></div>:<><div className="pending-state"><LockKeyhole size={19}/><div><strong>{c.formPending}</strong><p>{c.formPendingText}</p></div></div><form className="lead-form" aria-label={c.formTitle} onSubmit={e=>e.preventDefault()}><fieldset disabled><div className="form-row"><label>{c.name}<input autoComplete="name" name="name" required/></label><label>{c.company}<input autoComplete="organization" name="company" required/></label></div><label>{c.contactLabel}<input name="contact" required/></label><label>{c.problemLabel}<select name="problem" required defaultValue=""><option value="">{c.choose}</option>{c.options.map(o=><option key={o}>{o}</option>)}</select></label><label className="consent-check"><input type="checkbox" required/><span>{c.consent}</span></label><button className="button disabled-button" type="submit">{c.send}<ArrowRight size={16}/></button></fieldset></form><DemoLink locale={locale} className="text-link">{d.demoCta}</DemoLink></>}{config.consultationCalendarUrl&&<a className="text-link" href={externalUrl(config.consultationCalendarUrl,locale,query)}>{c.calendar}<ArrowRight size={16}/></a>}</>:modal==='cookies'?<><span className="modal-symbol"><ShieldCheck size={25}/></span><h2 id="modal-title">{c.cookieTitle}</h2><p>{c.cookieText}</p><div className="preference-row"><div><strong>{c.essential}</strong><p>{c.essentialDesc}</p></div><span>{c.always}</span></div><label className="preference-row"><div><strong>{c.analytics}</strong><p>{c.analyticsDesc}</p></div><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)}/></label><button className="button teal-button" onClick={()=>saveConsent(analytics)}>{c.save}</button></>:<><span className="modal-symbol"><ShieldCheck size={25}/></span><h2 id="modal-title">{modal==='privacy'?c.privacy:modal==='policy'?c.cookies:c.legal}</h2><p>{c.legalPending}</p><button className="button teal-button" onClick={()=>setModal(null)}>{d.close}</button></>}
 </dialog></>
}
function WorkflowIcon(){return <ArrowRight size={25}/>}

